### ISSUE TITLE
What is the train data was used for training small vae?

### ISSUE THREAD

**Issue by SashaBurashnikova** [Elvenson/midiMe#16]
Hello,

Could you please clarify on which data you continue to train your smallvae model? is it only one music composition with augmentation or smth else? Because when i tried to run you code training small vae only on 1 augmented melody it doesn't give me any good samples.

Thank you in advance,
Sincerely yours,
Aleksandra

**Comment by Elvenson** [comment]
Hi there,
The input of the SmallVAE model should be a melody snippet, usually it is a monophonic piece. As how to generate one you can take this as a reference:
```
import magenta.music as m

def get_melody_ns(filename):
    """
    Convert melody Midi file to note sequence.
    :param filename: Midi file name.
    :return:
        Melody note sequences.
    """
    melody_ns = mm.midi_file_to_note_sequence(filename)
    melody_instrument = mm.infer_melody_for_sequence(melody_ns)

    notes = [note for note in melody_ns.notes if note.instrument == melody_instrument]
    del melody_ns.notes[:]
    melody_ns.notes.extend(
        sorted(notes, key=lambda note: note.start_time)
    )
    for i in range(len(melody_ns.notes) - 1):
        melody_ns.notes[i].end_time = melody_ns.notes[i + 1].start_time

    return melody_ns


ns = get_melody_ns("your midi file")
mm.sequence_proto_to_midi_file(ns, "output.mid")
```
Or you can take a look at this [code snippet](https://github.com/magenta/magenta/blob/master/magenta/models/music_vae/music_vae_generate.py#L135) from MusicVAE on how they extract appropriate dataset for interpolation.
You can also visit the official Google MidiMe website to see how they convert the original midi file to the training midi via this https://midi-me.glitch.me/ (under melodies section).
Other suggestion is you can increase the `encoded_z_size` ([in this code](https://github.com/Elvenson/midiMe/blob/master/configs.py#L100)) to a higher number since this parameter is responsible for encoding your melody, so higher dimension may capture your melody motif.
Hope this help!
